name: deploy-server-minecraft

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy-server-minecraft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Connecting to srv and running helm commands to initialize or upgrade charts
      - name: "Deploying Helm App 🚀"
        run: |
          mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config && export KUBECONFIG=~/.kube/config && \
          helm upgrade --install minecraft helm/minecraft --namespace minecraft --create-namespace
